### ISSUE TITLE
`blandr` was removed from CRAN

### ISSUE THREAD

**Issue by isaactpetersen** [deepankardatta/blandr#29] opened 2024-05-21 01:33 UTC
FYI, `blandr` was removed from CRAN (https://cran.r-project.org/web/packages/blandr/index.html). Here are the failed checks:
https://cran-archive.r-project.org/web/checks/2024/2024-05-10_check_results_blandr.html

Would it be possible to fix the checks and get it back on CRAN?

**Comment by deepankardatta** [comment] 2024-05-21 05:11
Massive apologies. Due to work I've not had time to work on this properly.. I'm off to work in an hour. I'll do the fixes and re-submit it tomorrow to CRAN. Thanks for your patience.

**Comment by deepankardatta** [comment] 2024-05-21 05:13
I suspect the issue is that it won't allow external loading of good dataset from Bland's page (and I don't want to include them in the package without permission). I will fix. Also thanks for bringing to my attention.

**Comment by kwstat** [comment] 2024-05-22 15:34
Thanks for your prompt attention to this.

Note that this link: https://cran.r-project.org/web/packages/blandr/index.html also says 
```
Archived on 2024-05-10 as email to the maintainer is undeliverable. 
```
so be sure to fix the email address in `DESCRIPTION` file.

**Comment by deepankardatta** [comment] 2024-05-28 21:36
I'm not sure actually.

Apologies it's taken me longer than I thought. I've had to re-familarise myself with the code, and make changes. I think the final things left is to update some of the arguments in the code so that there's no errors and then re-submit.

I can't work out why the checks errored on some systems and not others - I wonder if the CRAN check servers hammered the webpage that errored out, and was therefore blocked, so causing the checks to fail. I may remove these functions temporarily.

I need to set-up the new checking system from GitHub that didn't exist when I first submitted the package.

I've made a new branch (0.6) to make these changes. I estimate another 2 days work to fix this. In the meantime I've attached the package that I've created on my MacOS system to see if this works for you temporarily.

[blandr_0.6.tar.gz](https://github.com/deepankardatta/blandr/files/15476207/blandr_0.6.tar.gz)

**Comment by isaactpetersen** [comment] 2024-06-06 12:39
For some reason, I can no longer install the package from GitHub on the main branch:

```r
> remotes::install_github("deepankardatta/blandr")
Using github PAT from envvar GITHUB_PAT. Use `gitcreds::gitcreds_set()` and unset GITHUB_PAT in .Renviron (or elsewhere) if you want to use the more secure git credential store instead.
Downloading GitHub repo deepankardatta/blandr@HEAD
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   checking for file 'C:\Users\Isaac\AppData\Local\Temp\RtmpikB98Y\remotesbe381479c9a\deepankardatta-blandr-7eb5c64/DESCRIPTION' ...
   checking for file 'C:\Users\Isaac\AppData\Local\Temp\RtmpikB98Y\remotesbe381479c9a\deepankardatta-blandr-7eb5c64/DESCRIPTION' ... 
✔  checking for file 'C:\Users\Isaac\AppData\Local\Temp\RtmpikB98Y\remotesbe381479c9a\deepankardatta-blandr-7eb5c64/DESCRIPTION'
─  preparing 'blandr': (886ms)
   checking DESCRIPTION meta-information ...
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'blandr_0.6.tar.gz'

Installing package into ‘C:/R/Packages’
(as ‘lib’ is unspecified)
* installing *source* package 'blandr' ...
** using staged installation
** R
Error in .install_package_code_files(".", instdir) : 
files in 'C:/Users/Isaac/AppData/Local/Temp/RtmpEzBmKA/R.INSTALL148b8398c52a0/blandr/R' missing from 'Collate' field:
  blandr.statistics.formula.R
ERROR: unable to collate and parse R files for package 'blandr'
* removing 'C:/R/Packages/blandr'
* restoring previous 'C:/R/Packages/blandr'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Isaac/AppData/Local/Temp/RtmpikB98Y/filebe38e2869d9/blandr_0.6.tar.gz’ had non-zero exit status
```

**Comment by deepankardatta** [comment] 2024-06-09 11:54
> I'm sorry to be anxious, but can you give a status update? (I have coworkers that are starting to have discussions about the need to switch to a different set of R functions for Bland Altman).

Apologies. it's been re-submitted today.

**Comment by deepankardatta** [comment] 2024-06-09 11:56
> For some reason, I can no longer install the package from GitHub on the main branch:
> 
> ```r
> > remotes::install_github("deepankardatta/blandr")
> Using github PAT from envvar GITHUB_PAT. Use `gitcreds::gitcreds_set()` and unset GITHUB_PAT in .Renviron (or elsewhere) if you want to use the more secure git credential store instead.
> Downloading GitHub repo deepankardatta/blandr@HEAD
> ── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>    checking for file 'C:\Users\Isaac\AppData\Local\Temp\RtmpikB98Y\remotesbe381479c9a\deepankardatta-blandr-7eb5c64/DESCRIPTION' ...
>    checking for file 'C:\Users\Isaac\AppData\Local\Temp\RtmpikB98Y\remotesbe381479c9a\deepankardatta-blandr-7eb5c64/DESCRIPTION' ... 
> ✔  checking for file 'C:\Users\Isaac\AppData\Local\Temp\RtmpikB98Y\remotesbe381479c9a\deepankardatta-blandr-7eb5c64/DESCRIPTION'
> ─  preparing 'blandr': (886ms)
>    checking DESCRIPTION meta-information ...
> ✔  checking DESCRIPTION meta-information
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  building 'blandr_0.6.tar.gz'
> 
> Installing package into ‘C:/R/Packages’
> (as ‘lib’ is unspecified)
> * installing *source* package 'blandr' ...
> ** using staged installation
> ** R
> Error in .install_package_code_files(".", instdir) : 
> files in 'C:/Users/Isaac/AppData/Local/Temp/RtmpEzBmKA/R.INSTALL148b8398c52a0/blandr/R' missing from 'Collate' field:
>   blandr.statistics.formula.R
> ERROR: unable to collate and parse R files for package 'blandr'
> * removing 'C:/R/Packages/blandr'
> * restoring previous 'C:/R/Packages/blandr'
> Warning message:
> In i.p(...) :
>   installation of package ‘C:/Users/Isaac/AppData/Local/Temp/RtmpikB98Y/filebe38e2869d9/blandr_0.6.tar.gz’ had non-zero exit status
> ```

Apologies. I swapped the default branch to the 0.6-development branch which I suspect is the problem. The "master" branch was the stable branch. Hopefully the submitted 0.6 version will get approved quickly, and I can roll everything back into the "master" branch. I'm going to go and swap the default branch back to "master" if this helps.

**Comment by deepankardatta** [comment] 2024-06-09 12:23
Further update. The CRAN package has passed the Windows and Debian automated checks with 1 note (seems to always do this with the vignette builder). It passed on 2 versions of MacOS, with 2 slightly related versions of R (both 4.x versions).

It does mention a 10-day turn around time, however I attach a working version of the library here.

[blandr_0.6.0.tar.gz](https://github.com/user-attachments/files/15751733/blandr_0.6.0.tar.gz)

However I've merged everything back into the "master" branch now.

You should also be able to install with the following:
```
install.packages("devtools")
devtools::install_github("deepankardatta/blandr")
```

**Comment by deepankardatta** [comment] 2024-06-09 12:26
@isaactpetersen @kwstat see above for updates

**Comment by michaelbach** [comment] 2024-06-09 18:03
Congratulations (well, nearly) and THANK YOU! 
What a PITA: First you provide a major service to the community, and then it comes back to bite to because of some changed dependencies etc. Clearly disrupts other projects on your palette, so: thank you for making the time.

**Comment by deepankardatta** [comment] 2024-06-10 06:48
> Congratulations (well, nearly) and THANK YOU! What a PITA: First you provide a major service to the community, and then it comes back to bite to because of some changed dependencies etc. Clearly disrupts other projects on your palette, so: thank you for making the time.

No thank you. It's quite nice getting an appreciative message.

It's an interesting experience in maintenance of packages. I'm still not totally sure why the CRAN build failed a month ago to get the de-listing, although not updating my email compounded the error (I'm still with the same organisation, I'm now onto my 4th email as they keep on changing the domain, and the re-directs obviously failed at some point).

Sorry it's taken time to do this as I've had to re-learn R, and then work out the new updated R packages which don't quite work like they did 7 years ago!

**Comment by deepankardatta** [comment] 2024-06-10 06:54
Final update for this issue, which I can now close! blandr is now back on CRAN: https://cran.r-project.org/web/packages/blandr/index.html

Hopefully I've put some measures in place to make it that this does not happen again. However, now that I'm back in the flow, I'm going to use the next month to do some updates to other issues (I wanted to get blandr back on CRAN ASAP, before doing some other things). You can see this on the 0.6.1-development branch. This will also allow me to explore updating the Jamovi module as well.

I think after this I might ask a few people what they use most in the module, or what they (potentially!!!!!) want added.

**Closed by deepankardatta** 2024-06-10 06:54 UTC

**Comment by kwstat** [comment] 2024-06-10 13:43
Thanks so much for persevering and jumping through all the hurdles to get the package back on CRAN!
